[project]
name = "django-redis-tasks"
version = "1.0.0"
description = "Django tasks backend using Redis queues"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.md"]
requires-python = ">=3.14"
authors = [
    { name = "David Nugent", email = "davidn@uniquode.io" }
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 6.1",
]
dependencies = [
    "django>=6.1",
    "django-queues[redis]>=1.2.0,<2.0.0",
]

[project.urls]
Source = "https://github.com/deeprave/django-redis-tasks"
Issues = "https://github.com/deeprave/django-redis-tasks/issues"
Changelog = "https://github.com/deeprave/django-redis-tasks/releases"

[tool.pytest.ini_options]
minversion = "8.0"
asyncio_default_fixture_loop_scope = "function"
pythonpath = ["."]
testpaths = ["tests"]
python_files = ["test_*.py", "tests.py"]
DJANGO_SETTINGS_MODULE = "tests.settings"
django_find_project = false

[tool.ruff]
extend-exclude = [".django-src-*_cache"]

[dependency-groups]
dev = [
    "pytest-mock>=3.14.0",
    "pytest>=8.3.4",
    "ruff>=0.15.14",
    "testcontainers>=4.9.0",
    "ty>=0.0.69",
    "pytest-asyncio>=0.25.0",
    "pytest-django>=4.14.0",
]
[tool.uv]
default-groups = ["dev"]

[tool.setuptools.packages.find]
include = ["redis_tasks", "redis_tasks.*"]

[tool.ty.src]
include = ["redis_tasks"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
